#!/bin/bash
#
# projectfolders
#
# Creates skeleton project-folder heirarchies (based on specific workflow) in the current working directory
#
# usage:
#
#    projectfolders [projecttype]
#    
#        projecttypes: ('color', 'offline', 'online', 'deliverables')
#        
#        
#

USAGE="projectfolders [projecttype]:\n\n\tprojecttypes: 'color', 'online', 'deliverables'"

case "$1" in
    'color') mkdir -p ./COLOR/{ppro-conform,resolve_projects/_gallery-stills,resolve_renders/_cachefiles_,src_media/collected,ref-conform,xml/{00_collect,01_toResolve}};;
    'online') mkdir -p ./ONLINE/{ppro-online,_selfcontained,audio/mixes};;
    'deliverables') mkdir -p ./_DELIVERABLES/{approvals,broadcast,dvd/{disc_images,encore_dvd,encodes},audio_post,web/{youtube,vimeo,wmv}};;
    '') echo -e "\nusage: $USAGE\n";;
    *) echo -e "\nInvalid argument.\n\nusage: $USAGE\n";;
    

esac

